name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v2
      
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Установка зависимостей
        run: pip install -r requirements.txt
      
      - name: Установка pytest
        run: pip install pytest
      
      - name: Запуск тестов
        run: pytest
      
      - name: Сборка и упаковка
        run: |
          python setup.py build
          python setup.py sdist bdist_wheel
      
      - name: Публикация артефактов
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/
